name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        python -m unidic download


    - name: Test MeloTTS
      run: |
        python -c "
        import nltk
        nltk.download('averaged_perceptron_tagger_eng')

        from meloplus import MeloInference

        # Initialize model
        model = MeloInference(language='EN', device='cpu')

        # Test with a simple sentence
        text = 'Hello, this is a test.'

        # Get available speaker IDs
        speaker_ids = model.hps.data.spk2id
        print('Available speakers:', speaker_ids)

        # Test model inference
        print('Running inference...')
        output_path = 'en-us.wav'
        model.tts_to_file(text, speaker_ids['EN-US'], output_path, speed=1.0)
        print('Inference successful!')
        "
